# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gauthier/tmpRT/hub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gauthier/tmpRT/hub/tmpBuild

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gauthier/tmpRT/hub/tmpBuild/CMakeFiles /home/gauthier/tmpRT/hub/tmpBuild//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gauthier/tmpRT/hub/tmpBuild/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hub-cppCheck

# Build rule for target.
hub-cppCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-cppCheck
.PHONY : hub-cppCheck

# fast build rule for target.
hub-cppCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub-cppCheck.dir/build.make CMakeFiles/hub-cppCheck.dir/build
.PHONY : hub-cppCheck/fast

#=============================================================================
# Target rules for targets named hub-format

# Build rule for target.
hub-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-format
.PHONY : hub-format

# fast build rule for target.
hub-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub-format.dir/build.make CMakeFiles/hub-format.dir/build
.PHONY : hub-format/fast

#=============================================================================
# Target rules for targets named external

# Build rule for target.
external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external
.PHONY : external

# fast build rule for target.
external/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/external.dir/build.make src/CMakeFiles/external.dir/build
.PHONY : external/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/core.dir/build.make src/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named hub_static

# Build rule for target.
hub_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub_static
.PHONY : hub_static

# fast build rule for target.
hub_static/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/hub_static.dir/build.make src/CMakeFiles/hub_static.dir/build
.PHONY : hub_static/fast

#=============================================================================
# Target rules for targets named hub_shared

# Build rule for target.
hub_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub_shared
.PHONY : hub_shared

# fast build rule for target.
hub_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/hub_shared.dir/build.make src/CMakeFiles/hub_shared.dir/build
.PHONY : hub_shared/fast

#=============================================================================
# Target rules for targets named test-common

# Build rule for target.
test-common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-common
.PHONY : test-common

# fast build rule for target.
test-common/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-common.dir/build.make tests/CMakeFiles/test-common.dir/build
.PHONY : test-common/fast

#=============================================================================
# Target rules for targets named hub-test-all

# Build rule for target.
hub-test-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-all
.PHONY : hub-test-all

# fast build rule for target.
hub-test-all/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-all.dir/build.make tests/CMakeFiles/hub-test-all.dir/build
.PHONY : hub-test-all/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/Experimental.dir/build.make tests/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/Nightly.dir/build.make tests/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/Continuous.dir/build.make tests/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyMemoryCheck.dir/build.make tests/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyStart.dir/build.make tests/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyUpdate.dir/build.make tests/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyConfigure.dir/build.make tests/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyBuild.dir/build.make tests/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyTest.dir/build.make tests/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyCoverage.dir/build.make tests/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlyMemCheck.dir/build.make tests/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/NightlySubmit.dir/build.make tests/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalStart.dir/build.make tests/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalUpdate.dir/build.make tests/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalConfigure.dir/build.make tests/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalBuild.dir/build.make tests/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalTest.dir/build.make tests/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalCoverage.dir/build.make tests/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalMemCheck.dir/build.make tests/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ExperimentalSubmit.dir/build.make tests/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousStart.dir/build.make tests/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousUpdate.dir/build.make tests/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousConfigure.dir/build.make tests/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousBuild.dir/build.make tests/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousTest.dir/build.make tests/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousCoverage.dir/build.make tests/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousMemCheck.dir/build.make tests/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ContinuousSubmit.dir/build.make tests/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named hub-test-start

# Build rule for target.
hub-test-start: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-start
.PHONY : hub-test-start

# fast build rule for target.
hub-test-start/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-start.dir/build.make tests/CMakeFiles/hub-test-start.dir/build
.PHONY : hub-test-start/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-start

# Build rule for target.
hub-tests-bin-test-start: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-start
.PHONY : hub-tests-bin-test-start

# fast build rule for target.
hub-tests-bin-test-start/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-start.dir/build.make tests/CMakeFiles/hub-tests-bin-test-start.dir/build
.PHONY : hub-tests-bin-test-start/fast

#=============================================================================
# Target rules for targets named hub-test-core-io-InputOutput

# Build rule for target.
hub-test-core-io-InputOutput: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-io-InputOutput
.PHONY : hub-test-core-io-InputOutput

# fast build rule for target.
hub-test-core-io-InputOutput/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-io-InputOutput.dir/build.make tests/CMakeFiles/hub-test-core-io-InputOutput.dir/build
.PHONY : hub-test-core-io-InputOutput/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-io-InputOutput

# Build rule for target.
hub-tests-bin-test-core-io-InputOutput: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-io-InputOutput
.PHONY : hub-tests-bin-test-core-io-InputOutput

# fast build rule for target.
hub-tests-bin-test-core-io-InputOutput/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-io-InputOutput.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-io-InputOutput.dir/build
.PHONY : hub-tests-bin-test-core-io-InputOutput/fast

#=============================================================================
# Target rules for targets named hub-test-core-io-InputOutputSpeedCompare

# Build rule for target.
hub-test-core-io-InputOutputSpeedCompare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-io-InputOutputSpeedCompare
.PHONY : hub-test-core-io-InputOutputSpeedCompare

# fast build rule for target.
hub-test-core-io-InputOutputSpeedCompare/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-io-InputOutputSpeedCompare.dir/build.make tests/CMakeFiles/hub-test-core-io-InputOutputSpeedCompare.dir/build
.PHONY : hub-test-core-io-InputOutputSpeedCompare/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-io-InputOutputSpeedCompare

# Build rule for target.
hub-tests-bin-test-core-io-InputOutputSpeedCompare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-io-InputOutputSpeedCompare
.PHONY : hub-tests-bin-test-core-io-InputOutputSpeedCompare

# fast build rule for target.
hub-tests-bin-test-core-io-InputOutputSpeedCompare/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-io-InputOutputSpeedCompare.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-io-InputOutputSpeedCompare.dir/build
.PHONY : hub-tests-bin-test-core-io-InputOutputSpeedCompare/fast

#=============================================================================
# Target rules for targets named hub-test-core-io-Serializer

# Build rule for target.
hub-test-core-io-Serializer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-io-Serializer
.PHONY : hub-test-core-io-Serializer

# fast build rule for target.
hub-test-core-io-Serializer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-io-Serializer.dir/build.make tests/CMakeFiles/hub-test-core-io-Serializer.dir/build
.PHONY : hub-test-core-io-Serializer/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-io-Serializer

# Build rule for target.
hub-tests-bin-test-core-io-Serializer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-io-Serializer
.PHONY : hub-tests-bin-test-core-io-Serializer

# fast build rule for target.
hub-tests-bin-test-core-io-Serializer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-io-Serializer.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-io-Serializer.dir/build
.PHONY : hub-tests-bin-test-core-io-Serializer/fast

#=============================================================================
# Target rules for targets named hub-test-core-matrix-compatEigen3

# Build rule for target.
hub-test-core-matrix-compatEigen3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-matrix-compatEigen3
.PHONY : hub-test-core-matrix-compatEigen3

# fast build rule for target.
hub-test-core-matrix-compatEigen3/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-matrix-compatEigen3.dir/build.make tests/CMakeFiles/hub-test-core-matrix-compatEigen3.dir/build
.PHONY : hub-test-core-matrix-compatEigen3/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-matrix-compatEigen3

# Build rule for target.
hub-tests-bin-test-core-matrix-compatEigen3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-matrix-compatEigen3
.PHONY : hub-tests-bin-test-core-matrix-compatEigen3

# fast build rule for target.
hub-tests-bin-test-core-matrix-compatEigen3/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatEigen3.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatEigen3.dir/build
.PHONY : hub-tests-bin-test-core-matrix-compatEigen3/fast

#=============================================================================
# Target rules for targets named hub-test-core-matrix-compatOIIO

# Build rule for target.
hub-test-core-matrix-compatOIIO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-matrix-compatOIIO
.PHONY : hub-test-core-matrix-compatOIIO

# fast build rule for target.
hub-test-core-matrix-compatOIIO/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-matrix-compatOIIO.dir/build.make tests/CMakeFiles/hub-test-core-matrix-compatOIIO.dir/build
.PHONY : hub-test-core-matrix-compatOIIO/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-matrix-compatOIIO

# Build rule for target.
hub-tests-bin-test-core-matrix-compatOIIO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-matrix-compatOIIO
.PHONY : hub-tests-bin-test-core-matrix-compatOIIO

# fast build rule for target.
hub-tests-bin-test-core-matrix-compatOIIO/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatOIIO.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatOIIO.dir/build
.PHONY : hub-tests-bin-test-core-matrix-compatOIIO/fast

#=============================================================================
# Target rules for targets named hub-test-core-matrix-compatOpenCV

# Build rule for target.
hub-test-core-matrix-compatOpenCV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-matrix-compatOpenCV
.PHONY : hub-test-core-matrix-compatOpenCV

# fast build rule for target.
hub-test-core-matrix-compatOpenCV/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-matrix-compatOpenCV.dir/build.make tests/CMakeFiles/hub-test-core-matrix-compatOpenCV.dir/build
.PHONY : hub-test-core-matrix-compatOpenCV/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-matrix-compatOpenCV

# Build rule for target.
hub-tests-bin-test-core-matrix-compatOpenCV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-matrix-compatOpenCV
.PHONY : hub-tests-bin-test-core-matrix-compatOpenCV

# fast build rule for target.
hub-tests-bin-test-core-matrix-compatOpenCV/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatOpenCV.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-matrix-compatOpenCV.dir/build
.PHONY : hub-tests-bin-test-core-matrix-compatOpenCV/fast

#=============================================================================
# Target rules for targets named hub-test-core-Any

# Build rule for target.
hub-test-core-Any: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-Any
.PHONY : hub-test-core-Any

# fast build rule for target.
hub-test-core-Any/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-Any.dir/build.make tests/CMakeFiles/hub-test-core-Any.dir/build
.PHONY : hub-test-core-Any/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-Any

# Build rule for target.
hub-tests-bin-test-core-Any: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-Any
.PHONY : hub-tests-bin-test-core-Any

# fast build rule for target.
hub-tests-bin-test-core-Any/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-Any.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-Any.dir/build
.PHONY : hub-tests-bin-test-core-Any/fast

#=============================================================================
# Target rules for targets named hub-test-core-Buffer

# Build rule for target.
hub-test-core-Buffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-Buffer
.PHONY : hub-test-core-Buffer

# fast build rule for target.
hub-test-core-Buffer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-Buffer.dir/build.make tests/CMakeFiles/hub-test-core-Buffer.dir/build
.PHONY : hub-test-core-Buffer/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-Buffer

# Build rule for target.
hub-tests-bin-test-core-Buffer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-Buffer
.PHONY : hub-tests-bin-test-core-Buffer

# fast build rule for target.
hub-tests-bin-test-core-Buffer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-Buffer.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-Buffer.dir/build
.PHONY : hub-tests-bin-test-core-Buffer/fast

#=============================================================================
# Target rules for targets named hub-test-core-Macros

# Build rule for target.
hub-test-core-Macros: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-Macros
.PHONY : hub-test-core-Macros

# fast build rule for target.
hub-test-core-Macros/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-Macros.dir/build.make tests/CMakeFiles/hub-test-core-Macros.dir/build
.PHONY : hub-test-core-Macros/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-Macros

# Build rule for target.
hub-tests-bin-test-core-Macros: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-Macros
.PHONY : hub-tests-bin-test-core-Macros

# fast build rule for target.
hub-tests-bin-test-core-Macros/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-Macros.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-Macros.dir/build
.PHONY : hub-tests-bin-test-core-Macros/fast

#=============================================================================
# Target rules for targets named hub-test-core-Matrix

# Build rule for target.
hub-test-core-Matrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-Matrix
.PHONY : hub-test-core-Matrix

# fast build rule for target.
hub-test-core-Matrix/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-Matrix.dir/build.make tests/CMakeFiles/hub-test-core-Matrix.dir/build
.PHONY : hub-test-core-Matrix/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-Matrix

# Build rule for target.
hub-tests-bin-test-core-Matrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-Matrix
.PHONY : hub-tests-bin-test-core-Matrix

# fast build rule for target.
hub-tests-bin-test-core-Matrix/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-Matrix.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-Matrix.dir/build
.PHONY : hub-tests-bin-test-core-Matrix/fast

#=============================================================================
# Target rules for targets named hub-test-core-MatrixT

# Build rule for target.
hub-test-core-MatrixT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-MatrixT
.PHONY : hub-test-core-MatrixT

# fast build rule for target.
hub-test-core-MatrixT/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-MatrixT.dir/build.make tests/CMakeFiles/hub-test-core-MatrixT.dir/build
.PHONY : hub-test-core-MatrixT/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-MatrixT

# Build rule for target.
hub-tests-bin-test-core-MatrixT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-MatrixT
.PHONY : hub-tests-bin-test-core-MatrixT

# fast build rule for target.
hub-tests-bin-test-core-MatrixT/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-MatrixT.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-MatrixT.dir/build
.PHONY : hub-tests-bin-test-core-MatrixT/fast

#=============================================================================
# Target rules for targets named hub-test-core-MatrixTs

# Build rule for target.
hub-test-core-MatrixTs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-MatrixTs
.PHONY : hub-test-core-MatrixTs

# fast build rule for target.
hub-test-core-MatrixTs/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-MatrixTs.dir/build.make tests/CMakeFiles/hub-test-core-MatrixTs.dir/build
.PHONY : hub-test-core-MatrixTs/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-MatrixTs

# Build rule for target.
hub-tests-bin-test-core-MatrixTs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-MatrixTs
.PHONY : hub-tests-bin-test-core-MatrixTs

# fast build rule for target.
hub-tests-bin-test-core-MatrixTs/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-MatrixTs.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-MatrixTs.dir/build
.PHONY : hub-tests-bin-test-core-MatrixTs/fast

#=============================================================================
# Target rules for targets named hub-test-core-MatrixXD

# Build rule for target.
hub-test-core-MatrixXD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-MatrixXD
.PHONY : hub-test-core-MatrixXD

# fast build rule for target.
hub-test-core-MatrixXD/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-MatrixXD.dir/build.make tests/CMakeFiles/hub-test-core-MatrixXD.dir/build
.PHONY : hub-test-core-MatrixXD/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-MatrixXD

# Build rule for target.
hub-tests-bin-test-core-MatrixXD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-MatrixXD
.PHONY : hub-tests-bin-test-core-MatrixXD

# fast build rule for target.
hub-tests-bin-test-core-MatrixXD/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-MatrixXD.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-MatrixXD.dir/build
.PHONY : hub-tests-bin-test-core-MatrixXD/fast

#=============================================================================
# Target rules for targets named hub-test-core-MetaData

# Build rule for target.
hub-test-core-MetaData: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-MetaData
.PHONY : hub-test-core-MetaData

# fast build rule for target.
hub-test-core-MetaData/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-MetaData.dir/build.make tests/CMakeFiles/hub-test-core-MetaData.dir/build
.PHONY : hub-test-core-MetaData/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-MetaData

# Build rule for target.
hub-tests-bin-test-core-MetaData: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-MetaData
.PHONY : hub-tests-bin-test-core-MetaData

# fast build rule for target.
hub-tests-bin-test-core-MetaData/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-MetaData.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-MetaData.dir/build
.PHONY : hub-tests-bin-test-core-MetaData/fast

#=============================================================================
# Target rules for targets named hub-test-core-Types

# Build rule for target.
hub-test-core-Types: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-core-Types
.PHONY : hub-test-core-Types

# fast build rule for target.
hub-test-core-Types/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-core-Types.dir/build.make tests/CMakeFiles/hub-test-core-Types.dir/build
.PHONY : hub-test-core-Types/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-core-Types

# Build rule for target.
hub-tests-bin-test-core-Types: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-core-Types
.PHONY : hub-tests-bin-test-core-Types

# fast build rule for target.
hub-tests-bin-test-core-Types/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-core-Types.dir/build.make tests/CMakeFiles/hub-tests-bin-test-core-Types.dir/build
.PHONY : hub-tests-bin-test-core-Types/fast

#=============================================================================
# Target rules for targets named hub-test-end

# Build rule for target.
hub-test-end: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-test-end
.PHONY : hub-test-end

# fast build rule for target.
hub-test-end/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-test-end.dir/build.make tests/CMakeFiles/hub-test-end.dir/build
.PHONY : hub-test-end/fast

#=============================================================================
# Target rules for targets named hub-tests-bin-test-end

# Build rule for target.
hub-tests-bin-test-end: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests-bin-test-end
.PHONY : hub-tests-bin-test-end

# fast build rule for target.
hub-tests-bin-test-end/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests-bin-test-end.dir/build.make tests/CMakeFiles/hub-tests-bin-test-end.dir/build
.PHONY : hub-tests-bin-test-end/fast

#=============================================================================
# Target rules for targets named hub-tests

# Build rule for target.
hub-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub-tests
.PHONY : hub-tests

# fast build rule for target.
hub-tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hub-tests.dir/build.make tests/CMakeFiles/hub-tests.dir/build
.PHONY : hub-tests/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... hub-cppCheck"
	@echo "... hub-format"
	@echo "... hub-tests"
	@echo "... hub-tests-bin-test-core-Any"
	@echo "... hub-tests-bin-test-core-Buffer"
	@echo "... hub-tests-bin-test-core-Macros"
	@echo "... hub-tests-bin-test-core-Matrix"
	@echo "... hub-tests-bin-test-core-MatrixT"
	@echo "... hub-tests-bin-test-core-MatrixTs"
	@echo "... hub-tests-bin-test-core-MatrixXD"
	@echo "... hub-tests-bin-test-core-MetaData"
	@echo "... hub-tests-bin-test-core-Types"
	@echo "... hub-tests-bin-test-core-io-InputOutput"
	@echo "... hub-tests-bin-test-core-io-InputOutputSpeedCompare"
	@echo "... hub-tests-bin-test-core-io-Serializer"
	@echo "... hub-tests-bin-test-core-matrix-compatEigen3"
	@echo "... hub-tests-bin-test-core-matrix-compatOIIO"
	@echo "... hub-tests-bin-test-core-matrix-compatOpenCV"
	@echo "... hub-tests-bin-test-end"
	@echo "... hub-tests-bin-test-start"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... core"
	@echo "... external"
	@echo "... hub-test-all"
	@echo "... hub-test-core-Any"
	@echo "... hub-test-core-Buffer"
	@echo "... hub-test-core-Macros"
	@echo "... hub-test-core-Matrix"
	@echo "... hub-test-core-MatrixT"
	@echo "... hub-test-core-MatrixTs"
	@echo "... hub-test-core-MatrixXD"
	@echo "... hub-test-core-MetaData"
	@echo "... hub-test-core-Types"
	@echo "... hub-test-core-io-InputOutput"
	@echo "... hub-test-core-io-InputOutputSpeedCompare"
	@echo "... hub-test-core-io-Serializer"
	@echo "... hub-test-core-matrix-compatEigen3"
	@echo "... hub-test-core-matrix-compatOIIO"
	@echo "... hub-test-core-matrix-compatOpenCV"
	@echo "... hub-test-end"
	@echo "... hub-test-start"
	@echo "... hub_shared"
	@echo "... hub_static"
	@echo "... test-common"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

