# CMake generated Testfile for 
# Source directory: /home/gauthier/tmpRT/hub/tests
# Build directory: /home/gauthier/tmpRT/hub/tmpBuild/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(hub-test-start "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-start")
set_tests_properties(hub-test-start PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-io-InputOutput "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-io-InputOutput")
set_tests_properties(hub-test-core-io-InputOutput PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-io-InputOutputSpeedCompare "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-io-InputOutputSpeedCompare")
set_tests_properties(hub-test-core-io-InputOutputSpeedCompare PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-io-Serializer "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-io-Serializer")
set_tests_properties(hub-test-core-io-Serializer PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-matrix-compatEigen3 "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-matrix-compatEigen3")
set_tests_properties(hub-test-core-matrix-compatEigen3 PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-matrix-compatOIIO "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-matrix-compatOIIO")
set_tests_properties(hub-test-core-matrix-compatOIIO PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-matrix-compatOpenCV "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-matrix-compatOpenCV")
set_tests_properties(hub-test-core-matrix-compatOpenCV PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-Any "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-Any")
set_tests_properties(hub-test-core-Any PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-Buffer "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-Buffer")
set_tests_properties(hub-test-core-Buffer PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-Macros "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-Macros")
set_tests_properties(hub-test-core-Macros PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-Matrix "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-Matrix")
set_tests_properties(hub-test-core-Matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-MatrixT "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-MatrixT")
set_tests_properties(hub-test-core-MatrixT PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-MatrixTs "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-MatrixTs")
set_tests_properties(hub-test-core-MatrixTs PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-MatrixXD "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-MatrixXD")
set_tests_properties(hub-test-core-MatrixXD PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-MetaData "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-MetaData")
set_tests_properties(hub-test-core-MetaData PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-core-Types "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-core-Types")
set_tests_properties(hub-test-core-Types PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
add_test(hub-test-end "/home/gauthier/tmpRT/hub/tmpBuild/tests/hub-test-end")
set_tests_properties(hub-test-end PROPERTIES  _BACKTRACE_TRIPLES "/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;130;add_test;/home/gauthier/tmpRT/hub/tests/CMakeLists.txt;0;")
subdirs("../_deps/catch2-build")
